# Generated by Django 4.0.5 on 2022-06-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nomr',
            new_name='nome',
        ),
    ]
